### ISSUE TITLE
lighten('black') is still black

### ISSUE THREAD

**Issue by lachenmayer** [wessberg/color#2]
Hi Frederik, thanks for creating this library - I'm currently using it in a TypeScript project and the API is really nice.

I'm trying to lighten a black color, but it remains black:

```js
const {lighten} = require("@wessberg/color")
console.log(lighten('black', 10)) // => '#000000'
console.log(lighten('#000000', 10)) // => '#000000'
```

([check it out on Runkit](https://runkit.com/embed/m5gg6497kasc))

It works just fine for other colors.

I had a look at the source for [`lightenHsl`](https://github.com/wessberg/color/blob/master/src/index.ts#L887), and the lightness is calculated as follows:

```js
Math.max(0, Math.min(100, ((100 + percentage) * parseFloat(L)) / 100))
```

(where `percentage = 10`)

For black, `L = 0`, so the resulting lightness value is `0`.
For `L = 50`, the resulting lightness is `55`.

In general, it seems strange that the percentage is proportional to the existing lightness value, because colors that are already light will become much lighter than darker colors. I expected the lightness to simply be added to the existing lightness, ie. that

for `L = 0`, the resulting lightness would be `10`,
and for `L = 50` it would be `60`.

in JS:

```js
Math.max(0, Math.min(100, parseFloat(L) + percentage))
```

This change would obviously affect all of the colors generated by your library so I don't know if this is something you'd want to do if you're relying on the way specific colors look already - just wanted to flag this as I'll unfortunately have to use a different library for the time being.

Anyway let me know if this makes sense & if you'd consider changing the behavior. Thanks a lot :)

**Comment by wessberg** [comment]
Hey there. Thanks for submitting this issue. Yeah, I've been wanting to address this for some time. The same goes for `saturate()` which can also lead to the exact same kind of issues when the `S` value is `0`.

I've released a new version (v1.0.5) that fixes the behavior of `lighten` and `saturate`.

**Comment by lachenmayer** [comment]
Awesome, thanks so much for the speedy fix :)

**Comment by lachenmayer** [comment]
Can confirm this works perfectly - thanks a lot!
